config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

    resources :users
    resources :friends
    resources :posts do
    resources :likes
    resources :comments, only: [:create]
  end

  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :body, presence: true
end

app/models/friend.rb
class Friend < ApplicationRecord

  belongs_to :user
  belongs_to(
    :friend_a,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id
  )
  belongs_to(
    :friend_b,
    class_name: "User",
    foreign_key: :other_user_id,
    primary_key: :id
  )
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  has_many :likes
  belongs_to :user
  has_one_attached :image
  validates :message, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts

  has_many(
    :a_friends,
    class_name: "Friend",
    foreign_key: :user_id,
    primary_key: :id
  )
  has_many(
    :b_friends,
    class_name: "Friend",
    foreign_key: :other_user_id,
    primary_key: :id
  )

  has_many :friend_as, through: :b_friends, source: :friend_a
  has_many :friend_bs, through: :a_friends, source: :friend_b

  has_one_attached :image
  has_many :likes

  has_secure_password
  has_many :comments

  validates :username, presence: true, uniqueness: true
  validates :password, presence: true
  validates :image, presence: true

  def friends
    friend_as + friend_bs
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :friendship_not_exists?
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end

  def friendship_not_exists?(other_user)
    (!Friend.where(user_id: session[:user_id], other_user_id: other_user).exists? &&
    !Friend.where(user_id: other_user, other_user_id: session[:user_id]).exists?)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # New route not required if not rendering new comment form.
  # def new
  #   @post = Post.find(params[:post_id])
  #   @comment = @post.comments.new
  # end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)

    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  # def index # redundant
  #   @post = Post.find(params[:post_id])
  #   @comments = @post.comments.order('created_at').reverse_order
  # end

  private
  def comment_params
    params.require(:comment).permit(:user_id, :body, :post_id)
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def index
  end

  def new
  end

  def create
    @friend = Friend.create(:user_id => params[:user_id], :other_user_id => params[:other_user_id])
    flash[:notice] = "Friend Added"
    redirect_to posts_url
  end

  def show
    @friend = User.find(params[:id])
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_post
  before_action :find_like

  def create
    if already_liked?
      @like.destroy
    else
      @post.likes.create(user_id: current_user.id)
    end
    respond_to do |format|
      format.html { redirect_to root_url }
      format.js
    end
  end

  private

  def find_post
    @post = Post.find(params[:post_id])
  end

  def find_like
    @like = @post.likes.find_by(user_id: current_user.id, post_id: params[:post_id])
  end

  def already_liked?
    Like.exists?(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # redundant as rendering the new post form in the index
  # def new
  #   @post = Post.new
  # end

  def create
    @post = Post.create(post_params)
    respond_to do |format|
      format.html { redirect_to root_url }
      format.js
    end
  end

  def index
    @user = User.find_by(id: session[:user_id])
    @posts = Post.order(created_at: :desc)
  end

  private

  def post_params
    params.require(:post).permit(:message, :user_id, :image)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash[:alert] = "Email or password is invalid"
      redirect_to root_url, notice: "Email or password is invalid"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      session[:expires_at] = Time.current + 12.hours
      redirect_to root_url
    else
      render :new
    end

  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="comments-div">
  <div class="commenter">
    <%= image_tag User.find(comment.user_id).image, class: "comment-profile-photo"%>
    <%= User.find(comment.user_id).username %>
  </div>
  <div class="comment-body">
    <%= comment.body %>
  </div>
</div>

app/views/comments/_form.html.erb
<div class="comment-form">
  <%= form_with model: [ post, post.comments.build ], local: false do |form| %>
    <%= form.text_field :body, class: "comment-entry-box", id: "comment-entry-box-#{ post.id }", placeholder: 'Enter your unsolicited advice here...', required: true%>

    <%= form.hidden_field :user_id, :value => current_user.id if current_user %>

    <%= form.submit "Comment", class: "comment-submit" %>
  <% end %>
</div>

app/views/comments/create.js.erb
document.querySelector("#top-comments-<%=@post.id%>").innerHTML =
  `<%= render @post.comments.order('created_at': :desc).limit(2) %>`;

document.querySelector("#all-comments-<%=@post.id%>").innerHTML =
  `<%= render @post.comments.order('created_at': :desc) %>`;

document.querySelector("#comment-entry-box-<%=@post.id%>").value = ""

app/views/friends/index.html.erb
<h1>Friends#index</h1>
<p>Find me in app/views/friends/index.html.erb</p>

app/views/friends/show.html.erb
<div class="friend_list">
<h3 class="friends-list-header"><%= @friend.username %>'s Filofax:</h3>
   <% @friend.friends.each do |friend| %>
     <%= link_to friend_path(friend.id) do %>
      <p><%= friend.username %></p>
     <% end %>
   <% end %>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Knitter</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link rel="icon"
    href="/k.png">
  </head>

  <body>
    <header>
      <div class="grid-container">
        <!-- <a href=""> -->
          <a href="/" id='logo-text'><img class="logo" src="/k.png">nitter</a>
          <div class="grid-item"></div>
          <div class="grid-item"></div>
          <div class="grid-item"></div>
          <div class="grid-item"></div>
        <!-- </a> -->
        <% if current_user %>
          <div class="grid-item">
            <%= link_to friend_path(current_user.id), class: "friends-page" do %>
              <%= image_tag current_user.image, id: "current-user-image"%>
            <% end %>
          </div>
          <div class="username"><%= current_user.username %></div>
          <div class="grid-item"><a><%= link_to "Log Out", logout_path %></a></div>

        <% else %>
          <div class="grid-item">
          </div>
          <div class="grid-item">
            <%= link_to "Sign Up", signup_path %>
          </div>
          <div class="grid-item-login">
            <div class="login-form">
              <%= render partial: 'sessions/form'%>
            </div>
          </div>
        <% end %>
      </div>
    </header>

    <main>
      <div class="left-container">
        <%= yield %>
      </div>

      <div class="right-container">
          <img class="adimage-div" src="/ads/jammie_dodgers.png">
          <img class="adimage-div" src="/ads/win_a_teapot.png">
          <img class="adimage-div" src="/ads/missing_cat.png">
          <img class="adimage-div" src="/ads/privacypolicy.PNG">
          <img class="adimage-div" src="/ads/icecream.PNG">
          <img class="adimage-div" src="/ads/head_scarves.png">
          <img class="adimage-div" src="/ads/ribena.PNG">
          <img class="adimage-div" src="/ads/kiwi_shaver.PNG">
          <img class="adimage-div" src="/ads/toast.PNG">
      </div>
    </main>
  </body>
</html>

app/views/likes/create.js.erb
document.querySelector("#number_likes_<%= @post.id %>").innerHTML = "<%= @post.likes.count %> <%= (@post.likes.count) == 1 ? 'Approval' : 'Approvals'%>";

app/views/posts/_form.html.erb
<%= form_with model: [ Post ], local: false, id: "post-form" do |form| %>
  <div id="post-input-div">
    <%= form.text_area :message, id: "post-message", placeholder: 'Ramble on...', required: true%>
    <%= form.file_field :image, id: "post-image" %>
  </div>
  <%= form.hidden_field :user_id, :value => current_user.id if current_user %>

  <%= form.submit "Submit", id: "post-submit" %>
<% end %>

app/views/posts/_post.html.erb
<div class="post-content-author">
  <div class="poster">
    <% if current_user %>
      <%= link_to friend_path(post.user_id), class: "link_to_friends" do %>
        <%= image_tag User.find(post.user_id).image, class: "post-profile-photo"%>
          <p id="user-name"><%= User.find(post.user_id).username %></p>
      <% end %>
    <% else %>
      <%= image_tag User.find(post.user_id).image, class: "post-profile-photo"%>
      <p id="user-name"><%= User.find(post.user_id).username %></p>
    <% end %>
      <% if current_user && friendship_not_exists?(User.find(post.user_id)) && post.user_id != current_user.id%>
        <%= link_to "Recruit Bridge Partner", friends_path(:user_id => current_user.id, :other_user_id => User.find(post.user_id).id), :method => :post, class: "friends-button" %>
      <% end %>

  </div>
  <div class="post-content">
    <% if post.image.attached? %>
    <div class="post-image-div">
    <%= image_tag post.image, class: "post-image"%>
    </div>
    <% end %>
    <p class="post"><%= post.message %></p>
  </div>
</div>
<div class="likes-comment-buttons">
  <div class="likes">
    <p id="number_likes_<%= post.id %>">
      <%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Approval' : 'Approvals'%>
    </p>
  </div>
  <div class="like-button-div">
  <% if current_user %>
    <%= button_to "That's nice, sweetie", post_likes_path(post), remote: true, class: "like-button", id: "like_button_#{post.id}"%>
  <% end %>
  </div>
  <button type="button" class="comments-toggle" id="<%= post.id %>">More Unsolicited Advice</button>
</div>


<div class="comments-content">
  <div class="top-comments" id="top-comments-<%=post.id%>">
    <%= render post.comments.order('created_at': :desc).limit(2) %>
  </div>

  <div class="all-comments" id="all-comments-<%=post.id%>">
    <%= render post.comments.order('created_at': :desc) %>
  </div>
</div>

<% if current_user %>
  <div class="new-comment-form">
    <div></div>
    <%= render partial: 'comments/form', locals: { post: post } %>
  </div>
<% end %>

app/views/posts/create.js.erb
var newDiv = document.createElement('div');
newDiv.className = "post-div";
newDiv.innerHTML = `<%= render partial: "posts/post", locals: { post: @post } %>`;

document.querySelector(".posts").insertBefore(
  newDiv,
  document.querySelector(".posts").childNodes[0]
)

document.querySelector("#post-message").value = ""
document.querySelector("#post-image").value = ""

$('.comments-toggle').click((e) => {
  $(`#all-comments-${e.target.id}`).toggle();
  $(`#top-comments-${e.target.id}`).toggle();
});

app/views/posts/index.html.erb
<p id=”notice”><%= notice %></p>
<% if current_user %>
  <div class="post-form-div">
    <div>
      <h3>Post:</h3>
    </div>
    <%= render partial: 'posts/form' %>
  </div>
<% end %>

<div class="posts">
  <% @posts.each do |post| %>
    <div class="post-div">
      <%= render partial: 'posts/post', locals: { post: post }  %>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<%# This form is now redundant as we are rendering the form in the index page - therefore propose to delete this page (but checking ) %>

<%= form_for @post do |form| %>
  <%= form.label :message %>
  <%= form.text_field :message %>
  <%= form.label :image %>
  <%= form.file_field :image %>

  <%= form.hidden_field :user_id, :value => current_user.id if current_user %>

  <%= form.submit "Submit" %>
<% end %>

app/views/users/new.html.erb
<div class="user-form">
  <div class="form-title"><h1>Sign Up</h1></div>
  <%= form_for @user do |form| %>
    <div class="form-field">
      <div class="field-label">
        <%= form.label :username %>
      </div>
      <div class="field-input">
        <%= form.text_field :username %>
        <div class="alert">
          <% @user.errors.full_messages_for(:username).each do |message| %>
            <div><%= message %></div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="form-field">
      <div class="field-label">
        <%= form.label :password %>
      </div>
      <div class="field-input">
        <%= form.password_field :password %>
        <div class="alert">
          <% @user.errors.full_messages_for(:password).each do |message| %>
            <div><%= message %></div>
            <% break %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="form-field">
      <div class="field-label">
        <%= form.label :image %>
      </div>
      <div class="field-input">
        <%= form.file_field :image %>
        <% @user.errors.full_messages_for(:image).each do |message| %>
          <div><%= message %></div>
          <% break %>
        <% end %>
      </div>
    </div>

    <input type="submit" class="form-submit" id="user-signup-submit">
    <%# <%= form.submit "Submit" %>
  <% end %>
</div>